### ISSUE TITLE
Bug Bounty

### ISSUE THREAD

**Issue by guillaC** [uploadcare/uploadcare-widget-tab-effects#39]
> If you think you ran into something in Uploadcare libraries which might have security implications, please hit us up at bugbounty@uploadcare.com or Hackerone.
> 
> We'll contact you personally in a short time to fix an issue through co-op and prior to any public disclosure.

Hello
I contacted you after discovering a bug. at bugbounty@uploadcare.com
Cdlt,

**Comment by dmitry-mukhin** [comment]
@guillaC 
We've not received anything, unfortunately :(
Could you resend the message?
Also, we have an invite only HackerOne program for proper processing these reports. Let us know if you want to be added there.

Thanks!

**Comment by dmitry-mukhin** [comment]
Found it. Will get back to you.
