### ISSUE TITLE
Crop widget allows free cropping even though crop dimensions have been restricted

### ISSUE THREAD

**Issue by jeroenkroese** [uploadcare/uploadcare-widget-tab-effects#9]
Hi there, 

I've stumbled across an issue with the crop tool of the effects tab. When I supply the widget instance with a file instance created from a CDN URL that already includes a crop modifier, the dimension restriction settings are not honoured. I'm able to crop freely, even though the crop settings are set at '3:2,2:3'. 

This only seems to be the case for the crop tool included in the effects tab. Please see the linked jsfiddle.net. If I comment out uploadcare.registerTab("preview", uploadcareTabEffects); the default crop tool included in the widget honours the restrictions as expected.

https://jsfiddle.net/579rjv0d/

Regards, Jeroen

**Comment by Zmoki** [comment]
@jeroenkroese sorry for late reply.

We are now released the new version of Effects Tab, `1.1.0`, with fix about it. You example with the new version works good - https://jsfiddle.net/wq77s2k4/

**Comment by jeroenkroese** [comment]
Hi @Zmoki. Thank you for fixing. It seems to be working now.
